// <auto-generated />
namespace TradeSatoshi.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TransferEnable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TransferEnable));
        
        string IMigrationMetadata.Id
        {
            get { return "201512211116476_TransferEnable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
